### ISSUE TITLE
Crash with E078 while browsing sample-based presets

### ISSUE THREAD

**Issue by stosem** [SynthstromAudible/DelugeFirmware#3809]
### Please describe the problem:

Deluge freezes with error `E078` when I browse Boards of Deluge 7 presets (which are heavy FX and are mostly sample based). I basically play a few notes and select the next preset, then Deluge crashes on a random preset.
Confirmed in the latest beta 1.3.0-880AE4A, but also exists in alpha and previous versions. And not only with BoD7, but BoD6, BoD5 as well (which are also sample-based). It seems OK with BoD4 (no samples here).

![Image](https://github.com/user-attachments/assets/3ed97f83-69b7-4c3c-a646-b6a28affbbba)

### What is the expected behavior?

Deluge shouldn't crash.

### When did you start noticing the issue?

just now and before

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Beta

### What is the firmware name:

1.3.0-BETA-880AE4A

### If possible provide the steps to reproduce the issue and upload additional media:

1. Turned on
2. Created a new synth clip
3. Load + Synth
4. Go to BoD presets
5. Choose a preset
6. Play a few notes
7. Switch to next
8. Repeat until Deluge crash with error (usually after 10-15 presets).

What other details could I provide that would be helpful?

**Comment by m-m-adams** [comment]
FYI this won't crash in the final release, it's a debug feature for betas. It's indicating a gremlin in the code that's been around since official v4.0 but hopefully we'll find it soon

**Comment by stosem** [comment]
BTW, if I press SELECT, it comes back, but now crashing more frequently (every second preset). Is there any way to debug this?

**Comment by m-m-adams** [comment]
If you can get it to happen reliably then sharing your steps might help find a fix but otherwise just use 1.2.1 and it won't crash. There's nothing user facing to debug and we don't know the root cause

**Comment by m-m-adams** [comment]
As far as I can tell this is fixed in nightly by #3617 

We aren't going to be able to fix it in beta as this has been around for years and needed a large refactoring. The freeze on this error code will be disabled automatically when the beta is changed to a release candidate

**Comment by stosem** [comment]
Thanks, @m-m-adams ! I can confirm, that I've not faced this issue in c1.2.1.
Unfortunately, I can still reproduce this bug in the latest nightly build: FW: v1_3_0-nightly+2025_06_20-893bf4b
Nothing special, I just turn on Delue and scroll BD7 presets, playing a few notes. By the way, some presets sound different than in c1.2.1 (no sound or clicks). Sometimes the PLAY button blinks (like a CPU overload).
In this nightly build the situation is even worse. After resuming (pressing SELECT) and scrolling further, Deluge freezes completely.

![Image](https://github.com/user-attachments/assets/e795178a-26ae-4486-a0b9-9f2a084a0947)

**Comment by Metamere** [comment]
This issue seems to cause a crashes consistently and much quicker when browsing presets while creating a synth row in a kit, i.e. in the SYNTH TO ROW menu. waiting for several multisample presets to load seems to cause the crash more quickly.

**Comment by o0dano0o** [comment]
I've encountered this a few times as well on the non-oled version.

**Comment by stosem** [comment]
I had a chance to debug the latest nightly with usb/sysex, and what I found.

The first error is always **E078** with the _same_ stack (I tried many times):
```
0x20174f73: _WriteNoCheck at src/RTT/SEGGER_RTT.c:436 <--- this line sometimes changing
# next lines are always the same:
0x2014326b: AudioFile::removeReason(char const*) at src/deluge/storage/audio/audio_file.cpp:501
0x20143311: AudioFileHolder::setAudioFile(AudioFile*, bool, bool, long) at src/deluge/storage/audio/audio_file_holder.cpp:74
0x20109aed: SampleHolder::setAudioFile(AudioFile*, bool, bool, long) at src/deluge/model/sample/sample_holder.cpp:117
```

Then, when I press SELECT (continue), it's crashing with different memory-related errors, like:

**M000**:
```
0x200e4a9f: GeneralMemoryAllocator::dealloc(void*) at src/deluge/memory/general_memory_allocator.cpp:283
0x200e4ccd: delugeDealloc at src/deluge/memory/general_memory_allocator.cpp:115
0x2014a519: StorageManager::loadInstrumentFromFile(Song*, InstrumentClip*, OutputType, bool, Instrument**, FilePointer*, String*, String*) at src/deluge/storage/storage_manager.cpp:367
0x2014cd1f: CStringArray::search(char const*, bool*) at src/deluge/util/container/array/c_string_array.cpp:105
```

**I009**:
```
0x2014e893: String::~String() at src/deluge/util/d_string.cpp:40
0x20061ea4: icciar_read_complete at src/RZA1/compiler/asm/irqfiq_handler.S:161
0x200d5619: View::navigateThroughPresetsForInstrumentClip(long, ModelStackWithTimelineCounter*, bool) at src/deluge/gui/views/view.cpp:2563
0x2016f8f0: deluge::dsp::AbsValueFollower::runEnvelope(float, float, float) at src/deluge/dsp/envelope_follower/absolute_value.cpp:29 (discriminator 1)
```

The sysex output during the first E078 crash was:
```
@123.0331: storage_manager.cpp:331: opening instrument file -  SYNTHS/BD7 15-CIRCUITRY SERENITY  from FP  106052
@123.0331: storage_manager.cpp:287: openFilePointer
@124.0997: sample_low_level_reader.cpp:280: setupClustersForPlayFromByte fail
@124.0997: sample_low_level_reader.cpp:281: byte:  1212332
@124.0997: time_stretcher.cpp:937: setupNewPlayHead failed. Sticking with old
@124.6268: audio_engine.cpp:495: direness:  3
@124.7650: audio_engine.cpp:495: direness:  4
@124.8892: audio_engine.cpp:495: direness:  3
# .... different numbers ....
@127.0148: audio_engine.cpp:495: direness:  5
@127.1388: audio_engine.cpp:495: direness:  4
@127.2629: audio_engine.cpp:495: direness:  3
@127.3613: d_string.cpp:137: setting string to itself
@127.3659: general_memory_allocator.cpp:92: 4321 bytes in stack 28447 free bytes in stack at SamplePlaybackGuide::getFinalClusterIndex
@127.3659: general_memory_allocator.cpp:92: 4353 bytes in stack 28415 free bytes in stack at SamplePlaybackGuide::getFinalClusterIndex
@127.3834: general_memory_allocator.cpp:92: 4377 bytes in stack 28391 free bytes in stack at SamplePlaybackGuide::getFinalClusterIndex
@127.3969: storage_manager.cpp:331: opening instrument file -  SYNTHS/BD7 16-SOFT ECHOES  from FP  106053
@127.3969: storage_manager.cpp:287: openFilePointer
@127.4212: sample.cpp:1764: reason dump---
```

and always has next lines:
```
@87.4804: sample_low_level_reader.cpp:280: setupClustersForPlayFromByte fail
@87.4804: sample_low_level_reader.cpp:281: byte:  1007420
@87.4804: time_stretcher.cpp:937: setupNewPlayHead failed. Sticking with old
@87.7746: sample_low_level_reader.cpp:280: setupClustersForPlayFromByte fail
@87.7746: sample_low_level_reader.cpp:281: byte:  2031416
@87.7747: time_stretcher.cpp:937: setupNewPlayHead failed. Sticking with old
@87.7756: sample_low_level_reader.cpp:280: setupClustersForPlayFromByte fail
@87.7757: sample_low_level_reader.cpp:281: byte:  1002254
....
@88.7380: d_string.cpp:137: setting string to itself
```

I hope this could help somehow.

**Comment by bzawad** [comment]
@stosem I narrowed it down to a specific commit in the issue I opened.  It's related to the SD card reading improvements. Not sure if that's helpful or if you're already aware.  I tried various things to fix it myself but wasn't successful.
https://github.com/SynthstromAudible/DelugeFirmware/issues/4223

**Comment by stosem** [comment]
Thanks, @seangoodvibes ! I can confirm, that last Release with cluster loading was fixed the problem!
